# Generated by Django 4.1.13 on 2024-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filtro',
            field=models.CharField(default='created_at', max_length=50),
        ),
    ]
